import Vector from '@/vector'

const v1 = new Vector([5, 2])
const v2 = new Vector([3, 1])
const zero2 = Vector.zero(2)
v1.print()
console.log(v1.length, zero2)
console.log(v1[1])
console.log(v1.toString())
console.log(v1.add(v2))
console.log(v1.subtract(v2))
console.log(Vector.subtract(v1, v2))
console.log(Vector.multiple(v1, 3))
console.log(Vector.multiple(v1, v2))
console.log(Vector.subtract(v1, zero2))
console.log(v2.multiple(3))
console.log(v2.norm(), v1.norm(), zero2.norm())
console.log(v2.normalize(), v1.normalize(), zero2.normalize())
console.log(v2.dot(v1), v2.dot(zero2))
v2.map(v => console.log(v))
